### ISSUE TITLE
bootstrap.py is too old

### ISSUE THREAD

**Issue by gforcada** [plone/buildout.jenkins#16]
`bootstrap.py` refuses to bootstrap, so we either need to use the newer version 1 or move to version 2.

I'm still suggesting version 1 because our `dev.cfg` points to Plone version 4.2.5 and I don't want to be the one breaking everything just to bump Plone to version 4.3.3 :)

**Comment by idgserpro** [comment]
A new release of zc.buildout 2.4.0 and bootstrap.py just came out, you can check it out.
